import { createGlobalTheme, globalStyle } from '@vanilla-extract/css';

import { theme } from './theme.css';

globalStyle('*, *::before, *::after', {
  boxSizing: 'border-box',
  WebkitFontSmoothing: 'antialiased',
  MozOsxFontSmoothing: 'grayscale',
});

globalStyle('html, body', {
  maxWidth: '100vw',
  minHeight: '100dvh',
});

globalStyle('body', {
  display: 'flex',
  flexDirection: 'column',
  margin: '0',
  fontSize: theme.fontSize.md,
  fontFamily: theme.font.jp,
  color: theme.color.txt.high,
});

globalStyle('h1, h2, h3, h4, p', {
  margin: 0,
});

createGlobalTheme(':root', theme, {
  font: {
    jp: `var(--font-noto-sans-jp)`,
    inter: `var(--font-inter)`,
    lato: `var(--font-lato)`,
  },
  fontSize: {
    xxxs: '10px',
    xxs: '11px',
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '18px',
    xl: '20px',
    xxl: '24px',
    xxxl: '32px',
  },
  lineHeight: {
    flat: '1.0',
    tight: '1.25',
    normal: '1.5',
    wide: '1.8',
  },
  space: {
    '0': '0px',
    '0.5': '2px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '7': '28px',
    '8': '32px',
    '9': '36px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    '28': '112px',
    '32': '128px',
  },
  radius: {
    '2': '2px',
    '4': '4px',
    '8': '8px',
    '12': '12px',
    '16': '16px',
    '24': '24px',
    '1000': '1000px',
  },
  pallete: {
    gradation: {
      1: {
        start: '#FFEDD5',
        end: '#D3FAF9',
      },
      2: {
        start: '#FED7AA',
        end: '#ADF4F2',
      },
      3: {
        start: '#FDBA74',
        end: '#75EBE9',
      },
      alpha: {
        1: {
          start: '#FFC68066',
          end: '#B2EAFC66',
        },
      },
    },
    red: {
      alpha: {
        2: '#FF5E4066',
        3: '#F34D3B99',
      },
    },
    gray: {
      1: '#FFFFFF',
      2: '#F9FAFB',
      3: '#F3F4F6',
      4: '#E5E7EB',
      5: '#D1D5DB',
      6: '#9CA3AF',
      7: '#6B7280',
      8: '#4B5563',
      9: '#374151',
      10: '#1F2937',
      11: '#111827',
      12: '#000000',
      alpha: {
        1: '#BFBFBF66',
        2: '#00000066',
        3: '#00000099',
        4: '#FFFFFFCC',
        5: '#0000000D',
        6: '#FFFFFF66',
      },
    },
    orange: {
      1: '#FFF7ED',
      2: '#FFEDD5',
      3: '#FED7AA',
      4: '#FDBA74',
      5: '#FB923C',
      6: '#F97316',
      7: '#EA580C',
      8: '#C2410C',
      9: '#9A3412',
      10: '#7C2D12',
    },
    turquoise: {
      1: '#EEFDFC',
      2: '#D3FAF9',
      3: '#ADF4F2',
      4: '#75EBE9',
      5: '#52E0E0',
      6: '#19BEC1',
      7: '#1899A2',
      8: '#1A7B84',
      9: '#1E636C',
      10: '#1D535C',
    },
    sky: {
      1: '#F0F9FF',
      2: '#E0F2FE',
      3: '#BAE6FD',
      4: '#7DD3FC',
      5: '#38BDF8',
      6: '#0EA5E9',
      7: '#0284C7',
      8: '#0369A1',
      9: '#075985',
      10: '#0C4A6E',
    },
    green: {
      1: '#F0FDF4',
      2: '#DCFCE7',
      3: '#BBF7D0',
      4: '#86EFAC',
      5: '#4ADE80',
      6: '#22C55E',
      7: '#16A34A',
      8: '#15803D',
      9: '#166534',
      10: '#14532D',
    },
    apricot: {
      1: '#FEF4F2',
      2: '#FDE8E3',
      3: '#FCD5CC',
      4: '#F8B7A9',
      5: '#F3927D',
      6: '#E8674B',
      7: '#D44C2E',
      8: '#B23C23',
      9: '#943520',
      10: '#7B3121',
    },
    yellow: {
      1: '#fefce8',
      2: '#fef9c3',
      3: '#fef08a',
      4: '#fde047',
      5: '#facc15',
      6: '#eab308',
      7: '#ca8a04',
      8: '#a16207',
      9: '#854d0e',
      10: '#713f12',
    },
    violet: {
      1: '#F5F3FF',
      2: '#EDE9FE',
      3: '#DDD6FE',
      4: '#C4B5FD',
      5: '#A78BFA',
      6: '#8B5CF6',
      7: '#7C3AED',
      8: '#6D28D9',
      9: '#5B21B6',
      10: '#4C1D95',
    },
    transparent: {
      1: '#F5F3FF',
      2: '#EDE9FE',
      3: '#DDD6FE',
      4: '#C4B5FD',
      5: '#A78BFA',
      6: '#8B5CF6',
      7: '#7C3AED',
      8: '#6D28D9',
      9: '#5B21B6',
      10: '#4C1D95',
    },
  },
  color: {
    txt: {
      strong: theme.pallete.gray['11'],
      inverted: theme.pallete.gray['1'],
      high: theme.pallete.gray['10'],
      medium: theme.pallete.gray['7'],
      low: theme.pallete.gray['6'],
      disabled: theme.pallete.gray['5'],
      error: theme.pallete.apricot['8'],
      'status-negative': theme.pallete.orange['6'],
      positive: theme.pallete.turquoise['7'],
    },
    link: {
      primary: theme.pallete.turquoise['6'],
    },
    bg: {
      default: theme.pallete.gray['1'],
      dark: theme.pallete.gray['3'],
      secondary: theme.pallete.gray['10'],
      'secondary-interactive-disabled': theme.pallete.gray['alpha']['2'],
      'secondary-interactive-pressed': theme.pallete.gray['5'],
      error: theme.pallete.apricot['6'],
      'error-right': theme.pallete.apricot['2'],
      negative: theme.pallete.orange['6'],
      'negative-right': theme.pallete.orange['2'],
      positive: theme.pallete.sky['6'],
      'positive-right': theme.pallete.sky['2'],
      information: theme.pallete.green['6'],
      'information-right': theme.pallete.green['2'],
      scrim: theme.pallete.gray['alpha']['2'],
      black: theme.pallete.gray['9'],
      'black-10': theme.pallete.gray['alpha']['5'],
      'black-60': theme.pallete.gray['alpha']['3'],
      chat: theme.pallete.orange['4'],
      light: theme.pallete.gray['alpha']['4'],
      'light-40': theme.pallete.gray['alpha']['6'],
      'red-60': theme.pallete.red['alpha']['3'],
    },
    icon: {
      default: theme.pallete.gray['10'],
      medium: theme.pallete.gray['7'],
      inverted: theme.pallete.gray['1'],
      weak: theme.pallete.gray['6'],
      disabled: theme.pallete.gray['5'],
      error: theme.pallete.apricot['8'],
      'status-negative': theme.pallete.orange['6'],
      positive: theme.pallete.turquoise['7'],
      green: theme.pallete.green['10'],
      sky: theme.pallete.sky['10'],
      apricot: theme.pallete.apricot['10'],
      transparent: 'transparent',
      gray: theme.pallete.gray['6'],
    },
    border: {
      light: theme.pallete.gray['1'],
      'interactive-default': theme.pallete.gray['4'],
      'interactive-disabled': theme.pallete.gray['alpha']['1'],
      dark: theme.pallete.gray['5'],
      black: theme.pallete.gray['9'],
      default: theme.pallete.gray['4'],
      secondary: theme.pallete.gray['9'],
      error: theme.pallete.apricot['7'],
      'status-negative': theme.pallete.orange['6'],
      positive: theme.pallete.turquoise['6'],
    },
  },
});
