import { createGlobalThemeContract } from '@vanilla-extract/css';

export const theme = createGlobalThemeContract(
  {
    font: {
      jp: null,
      inter: null,
      lato: null,
    },
    /**
     * ['10px','11px','12px','14px','16px','18px','20px','24px','32px']
     */
    fontSize: {
      xxxs: null,
      xxs: null,
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      xxl: null,
      xxxl: null,
    },
    lineHeight: {
      flat: null,
      tight: null,
      normal: null,
      wide: null,
    },
    space: {
      '0': 'space-0',
      '0.5': 'space-50',
      '1': 'space-100',
      '2': 'space-200',
      '3': 'space-300',
      '4': 'space-400',
      '5': 'space-500',
      '6': 'space-600',
      '7': 'space-700',
      '8': 'space-800',
      '9': 'space-900',
      '10': 'space-1000',
      '12': 'space-1200',
      '16': 'space-1600',
      '20': 'space-2000',
      '24': 'space-2400',
      '28': 'space-2800',
      '32': 'space-3200',
    },
    radius: {
      '2': null,
      '4': null,
      '8': null,
      '12': null,
      '16': null,
      '24': null,
      '1000': null,
    },
    pallete: {
      gradation: {
        1: {
          start: null,
          end: null,
        },
        2: {
          start: null,
          end: null,
        },
        3: {
          start: null,
          end: null,
        },
        alpha: {
          1: {
            start: null,
            end: null,
          },
        },
      },
      red: {
        alpha: {
          2: null,
          3: null,
        },
      },
      gray: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
        11: null,
        12: null,
        alpha: {
          1: null,
          2: null,
          3: null,
          4: null,
          5: null,
          6: null,
        },
      },
      orange: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      turquoise: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      sky: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      green: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      apricot: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      yellow: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      violet: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
      transparent: {
        1: null,
        2: null,
        3: null,
        4: null,
        5: null,
        6: null,
        7: null,
        8: null,
        9: null,
        10: null,
      },
    },
    color: {
      txt: {
        strong: null,
        inverted: null,
        high: null,
        medium: null,
        low: null,
        disabled: null,
        error: null,
        'status-negative': null,
        positive: null,
      },
      link: {
        primary: null,
      },
      bg: {
        default: null,
        dark: null,
        secondary: null,
        'secondary-interactive-disabled': null,
        'secondary-interactive-pressed': null,
        error: null,
        'error-right': null,
        negative: null,
        'negative-right': null,
        positive: null,
        'positive-right': null,
        information: null,
        'information-right': null,
        scrim: null,
        black: null,
        'black-10': null,
        'black-60': null,
        chat: null,
        light: null,
        'light-40': null,
        'red-60': null,
      },
      icon: {
        default: null,
        medium: null,
        inverted: null,
        weak: null,
        disabled: null,
        error: null,
        'status-negative': null,
        positive: null,
        green: null,
        sky: null,
        apricot: null,
        transparent: null,
        gray: null,
      },
      border: {
        light: null,
        'interactive-default': null,
        'interactive-disabled': null,
        dark: null,
        black: null,
        default: null,
        secondary: null,
        error: null,
        'status-negative': null,
        positive: null,
      },
    },
  },
  (value, path) => `--theme-${value || path.join('-')}`,
);
